config/default/core.entity_view_display.node.localgov_guides_overview.default.yml
config/default/core.entity_view_display.node.localgov_guides_page.default.yml
config/default/core.entity_view_display.node.localgov_news_article.default.yml
config/default/core.entity_view_display.node.localgov_services_landing.default.yml
config/default/core.entity_view_display.node.localgov_services_page.default.yml

So that the view looks closer to what an unauthenticated user will see. Admin tasks can be done in the admin interface rather than on the page itself.

Remove fields only visible to authenticated users from display

---

web/modules/custom/ecc_cookie_compliance/ecc_cookie_compliance.module

This change uses JavaScript to guard the GTM insert, as the previous attempt using PHP worked, but was subject to excessive caching. It also skips the noscript version being inserted, to ensure compliance.

Use JS for blocking GTM

---

nginx-conf/nginx.conf

This adds a no-index header when not served from gov.uk, to avoid indexing non-production environments.
On hold pending resolution of discussion in Jira

ECCW-401: Add noindex header

---

themes/custom/essex/css/overrides.css

This reverts this change as the image appears to be being cropped unnecessarily. As such, we would like to examine if there's a more appropriate fix in Drupal.

Revert #141  - ECCW-407-Reduce-size-of-image-on-media-with-text

---

web/modules/custom/ecc_cookie_compliance/ecc_cookie_compliance.libraries.yml
web/modules/custom/ecc_cookie_compliance/ecc_cookie_compliance.module
web/modules/custom/ecc_cookie_compliance/js/live_handler.js

This makes two changes to the analytics, to make the live experience better.
1. It wraps the analytics init script into a window function, so it can be triggered after page load, if the user agrees to other cookies
2. It listens to cookie consent change events and if analytics cookies are toggled it either calls the function from 1 or removes _ga cookies depending on the change.

ECCW-72: Analytics support

---

composer.json
composer.lock
nginx-conf/nginx.conf
patches/filesystem-chmod-0001.patch

Drupal will create image scales when accessed with a valid `itok` parameter, if they don't exist already. We use `try_files` in nginx to load the file directly without entering the Drupal controller if it's already present. Adding the if statement for header output prevents the rewrite triggered by `try_files` from working. Remove this to reinstate opportunistic creation.
In addition, the Drupal core uses a wrapped chmod function that handles getting the correct modes. This is used in multiple places, but especially the image scale generation code. This function assumes a well-behaved filesystem that allows chmod, but Azure blob storage doesn't. This patch changes the failure path of the function to report success if the file has a mode of `777`, even if the chmod fails. This is needed as …

ECCW-410: Allow opportunistic image scale generation

---

config/default/eu_cookie_compliance.settings.yml
web/modules/custom/ecc_cookie_compliance/ecc_cookie_compliance.libraries.yml
web/modules/custom/ecc_cookie_compliance/js/live_handler.js

Set missing ga filters in the cookie compliance script, so they're cleared out automatically, and replace the direct cookie unsetting with calls to the eu cookie compliance one. Trigger the automated clear-down at a couple of additional points, to improve behaviour due to window navigation hooks setting unwanted cookies.

ECCW-72: Improve cookie compliance

---

.gitlab-ci.yml
Dockerfile-nginx
nginx-conf/nginx.conf

Instead of using URL rewriting to add noindex, make it a container option. This is less flexible, but works reliably. The previous method couldn't be used in any circumstances that required further rewrites or conditionals.
This moves the overwritten nginx config file to a default site, using template environment variable interpolation. It also brings in the latest nginx version, upgrading from 1.22.1 to 1.23.4 at the time of writing.

ECCW-535: Move noindex logic to environment variables

---

Dockerfile-drupal

PHP FPM wasn't configured to pass logs through from workers, enable this without the decoration.

ECCW-547: Use console logs

---

.gitlab-ci.yml

The noindex environment variable should be on the nginx container, not the drupal one. This fixes the container yaml on deploy.

ECCW-535: Noindex support

---

.gitlab-ci.yml
Dockerfile-nginx
nginx-conf/nginx.conf

This mode is set by an environment variable, currently only active in preprod and prod, which redirects all requests handled by the Drupal backend to the current essex homepage if they don't match a URL whitelist OR there's no session cookie set.

ECCW-529: Add limited beta mode

---

nginx-conf/nginx.conf

This adds a URL that was missing from the original config that shouldn't be redirected.

ECCW-527: Add missing visit-us url

---

themes/custom/essex/css/overrides.css

Adds z-index to drupal editor menu to make it appear above the cookie banner

ECCW-519: Adds z-index to drupal editor menu

---

web/modules/custom/ecc_cookie_compliance/ecc_cookie_compliance.libraries.yml

This fixes a mis-specified library dependency that triggers log warnings.

Fix cookie compliance dependency

---

composer.json
composer.lock

The probe endpoint uses strftime, this applies a patch to switch to date to prevent it polluting logs.
This also upgrades to Drupal 9.5.9, with a security fix.

ECCW-548: Prevent strftime deprecation warnings on probe and upgrade to Drupal 9.5.9

---

nginx-conf/nginx.conf

Re-add the client max body size that was accidentally removed when switching to templated nginx config, rather than replacing the root config.

ECCW-575: Fix large file upload

---

config/default/system.performance.yml

Enable caching in the config, after testing directly for the last few weeks. This enables pre-processing of CSS and JS, and sets a max-age of 3 minutes as there's no active cache-clearing in AFD.

ECCW-604: Enable caching

---

.ddev/nginx_full/nginx-site.conf
nginx-conf/nginx.conf

If there's no canonical URL set in the environment, then we're looking for an empty string. Similarly, the variable should be contained within a string while interpolating.

Fix redirect logic when no canonical set

---

.gitlab-ci.yml

We've been pushing releases just as their release tag name, not updating the `latest` tag. We will continue to reference releases by their specific tag for deployments, but keeping `latest` up-to-date will assist with documenting maintenance commands.

Expose the latest release as the release tag in ACR

---

composer.json
composer.lock

Move the B2C login from a dev release to the Drupal release. Pin to beta, to allow Drupal 10 support.

Switch B2C to an official release

---

config/default/automated_cron.settings.yml

ECCI-439 stopped Cron running automatically. Set it to run every 900 seconds (15 minutes.)

ECCW-664: Set Automatic Cron to run every 900 seconds

---

config/default/user.role.localgov_editor.yml

ECCW-663: LP-18: Set permissions for editors to edit subsite overview and subsite page content types
Most permissions requested by Will Callaghan had been set already by the Config Alignment work but this has not been deployed yet to Preprod and Prod

ECCW-663: LP-18: Set permissions for editors to edit subsites

---

.gitlab-ci.yml

Gitlab pipeline fails when deploying _develop_ branch to Preprod. 
```
$ az acr import --force --name acreccukspre --source acreccuksdev.azurecr.io/portal-nginx-redirect:${CI_COMMIT_REF_SLUG} --image portal-nginx-redirect:${CI_COMMIT_REF_SLUG} --subscription "Essex County Council (Common)"
ERROR: (InvalidParameters) Operation registries-8843e49c-c660-11ee-9606-0242ac110002 failed. Resource /subscriptions/d4ffedb7-1180-4fee-9af9-6122b9fcbca5/resourceGroups/rg-ecc-common-uks-pre/providers/Microsoft.ContainerRegistry/registries/acreccukspre Unable to find manifest digest  Repo: portal-nginx-redirect Tag: develop Manifest: 
Code: InvalidParameters
Message: Operation registries-8843e49c-c660-11ee-9606-0242ac110002 failed. Resource /subscriptions/d4ffedb7-1180-4fee-9af9-6122b9fcbca5/resourceGrou …
```

Deployment to Preprod fails for develop branch.

---

.gitlab-ci.yml
composer.lock

This is to upgrade composer and `geocoder-php/common-http` to deal with a security issue and an abandoned package, both of which cause `composer audit` to fail.
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-24821
- One thing which wasn't immediately apparent while trying to resolve originally was that a `composer update composer/composer` was also required
- The latest `wodby/php` docker image didn't have Composer ^2.7, so a `composer self-update was added to the script section of the test job in the pipeline.

ECCW-0: Upgrade composer to address CVE-2024-24821.

---

composer.lock

Bumps the shared theme version to 1.0.18.
This removes the `grid-template-columns` property which was causing the massive gap between columns. See the shared theme [release](https://github.com/essexcountycouncil/ecc_theme/releases/tag/1.0.18).

ECCI-539: Excessive gap in featured teasers removed.

---

config/default/block.block.ecc_theme_gov_localgov_tabs_scarfolk.yml
config/default/system.site.yml

Re-enable Tabs block (already enabled on Prod, missing from new theme)

LP-88: Enable Tabs block. Revert frontpage node id.

---

.gitlab-ci.yml

Fix to allow deployment to Prod. My commit last month caused only the _latest_ tag container to be pushed to the Dev registry.

Gitlab change to create tagged containers.

---

config/default/pathauto.pattern.localgov_event.yml
config/default/views.view.localgov_events_listing.yml

https://eccservicetransformation.atlassian.net/jira/software/projects/FOS/boards/24?assignee=557058%3A8b7fbfd8-fba0-4c51-bd41-0b1d0e7d6ebe&selectedIssue=FOS-61
- Sets pathauto settings for events to follow the fostering path (we'll be updating this again later to make it more generic)
- Adds image for events teasers for the events listing page

updates pathauto settings for events, and events listing image style

---

config/default/block.block.ecc_theme_gov_breadcrumbs.yml
config/default/block.block.ecc_theme_gov_localgov_breadcrumbs_scarfolk.yml
config/default/views.view.localgov_events_listing.yml

Fixes https://eccservicetransformation.atlassian.net/jira/software/projects/LP/boards/25?label=ReleaseB&selectedIssue=LP-94
Two items here:
1. Adds breadcrumbs to the events listing page
2. Changes title of events listing page to 'Fostering events'

Lp 94/breadcrumbs events listing page

---

config/default/core.entity_view_display.media.image.localgov_event_thumbnail.yml

Fixes https://eccservicetransformation.atlassian.net/browse/LP-96
- Sets events in teaser view mode to use 3x2 image instead of square image

sets events teasers to use 3x2 image style

---

.github/workflows/comment.yml

in an issue_comment workflow:
- Get the PR from the comment using xt0rted/pull-request-comment-branch
- Set the correct REF_NAME from the PR
- Sets the correct comment issue-number
- Remove unnecessary steps.
https://github.com/xt0rted/pull-request-comment-branch?tab=readme-ov-file#outputs
The issue_comment workflow uses the develop branch so it's not possible to check these changes work until the branch has been merged to develop.

LP-118: Use ref name from PR in comment workflow.

---

.github/workflows/comment.yml
composer.json
composer.lock
config/default/core.extension.yml
config/default/mail_login.settings.yml

Enable Mail Login module so that users on Review Apps and Preprod can login to a local account using their email address - Essex user names are pulled from AD and can be very long.
This does not affect Prod as the login page only has the _Log in with Essex_ button.
- Add Remove Label step to stop_reviewapp. 
- Remove cleanup_reviewapp job (I can't remember why I thought we might need this as well as stop_reviewapp)
- Add Delete Revisions step to start_reviewapp job (just to remove any revisions that have been left running somehow)
- Remove deploy.sh step which doesn't work and is done properly in the next step

LP-118: Mail Login module, comment workflow fixes

---

.gitlab-ci.yml
config/default/block.block.ecc_theme_gov_breadcrumbs.yml
config/default/block.block.ecc_theme_gov_exposedformlocalgov_events_listingpage_all_events.yml
config/default/block.block.ecc_theme_gov_exposedformlocalgov_events_searchevents_page.yml
config/default/core.extension.yml
config/default/ecc_subsites.settings.yml
config/default/google_tag.settings.yml
config/default/pathauto.pattern.localgov_event.yml
config/default/preview_link.settings.yml
config/default/views.view.localgov_events_listing.yml
config/default/views.view.localgov_events_search.yml
web/modules/custom/ecc_deploy/ecc_deploy.deploy.php
web/modules/custom/ecc_deploy/ecc_deploy.info.yml
web/modules/custom/ecc_deploy/ecc_deploy.install
web/modules/custom/ecc_subsites/config/install/ecc_subsites.settings.yml

- views paths updated
- relevant blocks' "restricted to" paths updated
- pathauto patterns updated
- ecc_subsite's path updated
- `ecc_deploy` module added to do automated content updates when needed (in this case, updating a couple of menu paths).
- fixed google_tag settings and updated preview_link settings

FOS-97: Fixed events' breadcrumbs.

---

.github/workflows/comment.yml

Github workflow job to redeploy code to a review app without changing the database.
Another workflow job that can be triggered from a comment on the pull request. We now have:
- _/start_ - Start the Review App - deploy code, clone Dev database, run `drush deploy`
- _/rebuild_ - Deploy code, run `drush deploy`
- _/redeploy code_ - Deploy code
- _/stop_ - Delete the Review App, delete the database

ci(redeploy-code-job): Github workflow job to redeploy code

---

config/default/core.entity_form_display.node.localgov_subsites_overview.default.yml
config/default/core.entity_view_display.node.localgov_subsites_overview.default.yml
config/default/core.entity_view_display.node.localgov_subsites_overview.grid_item.yml
config/default/core.entity_view_display.node.localgov_subsites_overview.search_index.yml
config/default/core.entity_view_display.node.localgov_subsites_overview.search_result.yml
config/default/core.entity_view_display.node.localgov_subsites_overview.teaser.yml
config/default/field.field.node.localgov_subsites_overview.localgov_common_tasks.yml

Adds top tasks (localgov_common_tasks field) to subsite overview page content type.
Config only.
Thankfully, when comparing rendered output to a service landing page, the styles seem to just work.
https://eccservicetransformation.atlassian.net/browse/LP-120
Steps to test:
1. Find a service landing page, e.g. `/node/1657` and add some top tasks and save, to see what the goal is.
2. Find a subsite overview page, e.g. `node/1476` and edit.
3. Verify that top tasks is a tab, and allows you to enter links. Save the node.
4. Verify that the output matches the service landing page output for top tasks.

Add top tasks field to subsite overview pages content type. LP-120.

---

composer.lock

Update ecc_theme to 1.1.7. Includes:
- LP-101: Replace Twitter bird with X icon
- LP-124: Create template for service sub-landing to include an h2 to meet WCAG
- LP-125: Add right padding to accordion button to avoid clash at high zoom.
- LP-160: Make tabs region sticky immediately below toolbar.

LP-101: Update ecc_theme to 1.1.7 for X icon.

---

config/default/core.entity_form_display.media.document.default.yml
config/default/core.entity_form_display.media.image.default.yml
config/default/core.entity_form_display.media.remote_video.default.yml
config/default/core.entity_view_display.media.document.default.yml
config/default/core.entity_view_display.media.document.publication.yml
config/default/core.entity_view_display.media.image.default.yml
config/default/core.entity_view_display.media.image.localgov_event_thumbnail.yml
config/default/core.entity_view_display.media.image.localgov_featured.yml
config/default/core.entity_view_display.media.image.localgov_featured_large.yml
config/default/core.entity_view_display.media.image.localgov_newsroom_teaser.yml
config/default/core.entity_view_display.media.image.medium_8_7.yml
config/default/core.entity_view_display.media.image.responsive_3x2.yml
config/default/core.entity_view_display.media.image.responsive_banner.yml
config/default/core.entity_view_display.media.image.scale_crop_7_3_large.yml
config/default/core.entity_view_display.media.image.square.yml
config/default/core.entity_view_display.media.remote_video.default.yml
config/default/field.field.media.document.field_category.yml
config/default/field.field.media.image.field_category.yml
config/default/field.field.media.remote_video.field_category.yml
config/default/field.storage.media.field_category.yml
config/default/taxonomy.vocabulary.media_category.yml
config/default/user.role.localgov_editor.yml
config/default/views.view.media.yml
config/default/views.view.media_library.yml

Allows authorised users of Drupal to set categories on media items so media can be filtered when creating new pieces of content
N/A

ECCW 699: Management of media files

---

.gitlab-ci.yml

Fix pipeline error caused by tdnf expecting input.

ci(): Add -y to tdnf.

---

config/default/field.storage.paragraph.localgov_media_with_text_style.yml

includes `circle` as an option for the `style` field on media-with-text component.
Config only. Theme stuff is already present.

Add circular image style for media with text paragraph

---

config/default/core.entity_view_display.node.localgov_directories_page.default.yml

config change to swap the fieldset in use in localgov directory page content type to be a `h3` instead of a fieldset.
https://eccservicetransformation.atlassian.net/browse/LP-308

Use h3 instead of fieldset for directory page enquiries field group.

---

config/default/field.storage.node.localgov_subsites_theme.yml
web/modules/custom/ecc_subsites/ecc_subsites.module

ecc_subsites sets a white ecc logo for fostering already.
we now also include digital essex as a white-logo subsite theme.
https://eccservicetransformation.atlassian.net/jira/software/projects/LP/boards/25?selectedIssue=LP-232

Allow white logo for fostering and digital essex subsites

---

config/default/ecc_theme_gov.settings.yml

theme setting for ecc_theme_gov to turn on the "prepend DRAFT to node titles when they are unpublished" feature.
https://eccservicetransformation.atlassian.net/browse/LP-48

Turn on 'draft' setting for the gov theme

---

config/default/core.entity_view_display.node.localgov_directories_page.default.yml

Set directories page enquiries field fieldset to use h2 as label
https://eccservicetransformation.atlassian.net/browse/LP-308

Set enquiries fieldset to be h2 on directories page
