essexcountycouncil/essex-gov-uk-drupal

composer.lock, themes/custom/essex/css/overrides.css
Removes additional margin spacing on regions
=> ECC-40 responsiveness

themes/custom/essex/css/overrides.css
Also removes the icon from 'death of a notable person' alert banner
=> ECCW-117: Reduces width of alert banner border and size of icons

.gitignore, composer.json, composer.lock, config/default/core.extension.yml
We've agreed to manually configure in-situ for now.
=> ECCW-38: Introducing Matt's SSO module.

.gitlab-ci.yml, Dockerfile-drupal, deploy.sh
These changes enable the drush runner, isolated using socat to create a pty. It also fixes some deployment urls.
=> Automatic drush on deploy

.gitignore, assets/composer/settings.lando.php, assets/composer/settings.local.php, assets/composer/settings.php, config/default/openid_connect.client.essex.yml, config/default/openid_connect.client.nomensa.yml, config/default/openid_connect.settings.yml
OpenID Connect credentials and some config to be provided via .env vars.
=> ECCW-38: Added openid config to be populated via env vars.

config/default/cludo_search.settings.yml
Disable autocomplete on Cludo search
=> Disable autocomplete on Cludo search

config/default/linkit.linkit_profile.default.yml
So that content designers can create links to documents more easily.
=> Add documents to linkit profile

composer.json, composer.lock, config/default/eu_cookie_compliance.cookie_category.analytics_cookies.yml, config/default/eu_cookie_compliance.cookie_category.marketing_cookies.yml
I just downloaded a fresh version of the DB from DEV and this deployed ok on it with no nagging config errors.
=> ECCW-72: Sorting config issues.

config/default/block.block.cludosearchblock_2.yml, config/default/block.block.essex_localgov_mainnavigation_scarfolk.yml, config/default/block.block.eucookiesettingsblock.yml, config/default/eu_cookie_compliance.settings.yml, config/default/google_tag.container.ecc_public.yml
- Cludo searchbox removed from search page (ECCW-390)
- News segment on front page (views block) fixed (ECCW-138, ECCW-221
- Disabled javascript for localgov_eu_cookie_compliance instead of gull_settings.
=> ECCW-138, ECCW-221, ECCW-390 & ECCW-70

config/default/core.entity_form_display.node.localgov_services_sublanding.default.yml
For consistency with other content types
=> Change sublanding entity form to match others

web/modules/custom/ecc_cookie_compliance/css/ecc_cookie.css, web/modules/custom/ecc_cookie_compliance/ecc_cookie_compliance.libraries.yml
Copy cookie page improvements from ECCI-243. Is it time for us to move this into a shared module?
=> ECCW-413: Update cookie page styling

themes/custom/essex/css/overrides.css, themes/custom/essex/templates/layout/header.html.twig, themes/custom/essex/templates/layout/page.html.twig
For all pages other than the front page:
=> ECCW-398 search box in header

composer.json, composer.lock, patches/localgov-cookie-compliance-0001.patch
Adds the patch to enable the spinner, ahead of this being merged upstream.
=> ECCW-413: Add patch to LGD cookie compliance module

composer.json, composer.lock, config/default/core.extension.yml, config/default/health_check_url.settings.yml
This enables a healthcheck endpoint on the container app, to be used for replica probes.
=> ECCW-548: Enable health check module

Dockerfile-drupal
This is additional config that was needed in #212. Sorry, @siliconmeadow, I forgot to mark this as draft while I tested and found issues.
=> ECCW-547: Add missing FPM config

nginx-conf/nginx.conf
Mark the search page as accessible in limited beta mode
=> ECCW-529: Add csearch to beta allowed paths

.gitlab-ci.yml, Dockerfile-nginx-redirect, nginx-redirect/nginx.conf
Added nginx-based application that redirects to the www subdomain on the production site.
Created docker file to create an image using this config and edited pipeline to build and push the image, and to create a new revision of the application.
=> ECCW-24: Apex domain redirect

config/default/eu_cookie_compliance.cookie_category.analytics_cookies.yml
=> ECCW-545: Change description for analytics cookies.

.gitlab-ci.yml
This updates the autoscaling config to flex according to demand following observation, adds liveness probes in the Azure App Gateway k8s, and removes the now defunct migration test environment.
=> ECCW-548: autoscaling and probes

composer.lock
After the first upgrade to Drupal 9.5.9, the `composer.lock` file added some incompatible updates to various geo & and location modules it would appear. This had the knock-on effect of causing config imports failing due to modules not being present etc.
To resolve, I simply restored the pre-D9.5.9 upgrade `composer.lock` file and then performed the _de rigueur_ `composer update "drupal/core-*" --with-all-dependencies`
The config import then worked afterwards, and of course still has @longwave 's version of [laminas_directoros](https://github.com/longwave/laminas-diactoros).
=> ECCW-000: Composer lock file was adding/removing stuff.

config/default/core.extension.yml, web/modules/custom/ecc_cludo_search/ecc_cludo_search.info.yml, web/modules/custom/ecc_cludo_search/ecc_cludo_search.module
- Add invisible title to search form array to create label tag.
=> ECCW-590: Module for Essex specific cludo handling.

config/default/block.block.views_block__localgov_step_by_step_navigation_steps.yml
Forgot to commit the config export - sorry!
=> ECCW-597: Committing config change

.gitlab-ci.yml
Adds the SBOM generation and analysis steps to the GitLab pipeline, for monitoring software supply chain.
=> Add SBOM support

composer.lock, config/default/block.block.essex_localgov_tabs_scarfolk.yml, config/default/core.entity_form_display.node.localgov_step_by_step_overview.default.yml, config/default/gin.settings.yml
- ECCW-632: Show parent field at top of node edit form
- ECCW-628: Enable secondary toolbar, disable tabs block
- Drupal core update 9.5.11
=> ECCW-632 ECCW-628

config/default/core.extension.yml, config/default/localgov_login_redirect.settings.yml
redirects users to /admin/content when they login.
=> enables localgov_login_redirect module

composer.lock, config/default/essex.settings.yml
The major item in this PR is that [DRAFT] will be added to unpublished content.
=> Update/localgov base to 1.4.18

config/default/node.type.localgov_guides_overview.yml, config/default/node.type.localgov_guides_page.yml, config/default/node.type.localgov_news_article.yml, config/default/node.type.localgov_newsroom.yml, config/default/node.type.localgov_services_landing.yml, config/default/node.type.localgov_services_page.yml, config/default/node.type.localgov_services_status.yml, config/default/node.type.localgov_services_sublanding.yml, config/default/node.type.localgov_subsites_overview.yml, config/default/node.type.localgov_subsites_page.yml
Issue: https://eccservicetransformation.atlassian.net/jira/software/projects/LP/boards/25?selectedIssue=LP-9
=> sets preview as optional for all content types

composer.lock
=> Update ecc_theme to 1.0.14

composer.lock
=> Update ecc_theme to 1.0.15

.gitlab-ci.yml
=> Deploy to Preprod still fails - change CI_COMMIT_REF_SLUG to tag.

composer.lock
Adds the favicons to the Gov theme.
=> ECCI-675: Shared theme bumped, favicons added.

composer.lock
=> Update ecc_theme to 1.0.22

composer.lock
=> ECCW-000: Update ecc_theme to 1.0.26.

composer.lock
=> Update ecc_theme to 1.0.29

composer.lock
=> Update ecc_theme to 1.0.30.

config/default/field.field.media.document.field_media_document.yml
=> LP-75: Add .zip to allowed file formats.

config/default/user.role.localgov_editor.yml
Fixes: https://eccservicetransformation.atlassian.net/jira/software/projects/LP/boards/25?label=ReleaseB&selectedIssue=LP-93
=> allows editors to edit/delete taxonomy terms

composer.json, composer.lock
Patch for Preview Link module to fix error due to missing configuration.
https://www.drupal.org/project/preview_link/issues/3438117
=> LP-45: Patch for Preview Link module.

composer.lock
=> Update theme to 1.0.33

composer.lock
=> Update ecc_theme to 1.0.35

config/default/core.entity_view_display.media.image.localgov_event_thumbnail.yml, config/default/core.entity_view_display.node.localgov_event.card.yml, config/default/core.entity_view_mode.node.card.yml, config/default/views.view.localgov_events_listing.yml
Fixes (config) for https://eccservicetransformation.atlassian.net/jira/software/projects/LP/boards/25?label=ReleaseA&selectedIssue=LP-113
Creates a card view mode
Sets config for events to use this
Sets view for 'upcoming events' to use card
Resets view for events listing page to use image > view mode > event thumbnail
Resets image > view mode > event thumbnail to use Image style > square small
=> adds config for card view mode for events

composer.lock
=> Update ecc_theme to 1.0.36

config/default/views.view.localgov_events_listing.yml
Fixes :https://eccservicetransformation.atlassian.net/jira/software/projects/LP/boards/25?label=ReleaseA&selectedIssue=LP-99
=> sets events view to show 15 items

composer.lock, config/default/user.role.localgov_editor.yml
Fixes https://eccservicetransformation.atlassian.net/jira/software/projects/LP/boards/25?label=ReleaseA&selectedIssue=LP-112
=> allows editors to access the geo browser

composer.json, composer.lock
This is the equivalent of hotfix https://github.com/essexcountycouncil/essex-gov-uk-drupal/pull/437
**EITHER** merge that PR into main or this PR into develop 
=> NSD-418: Cookie form radio buttons fix.

.github/workflows/comment.yml
A new workflow to rebuild the Review App without resetting the database. This will be useful for making small code or config changes without losing any content changes and is quicker than cloning the database.
=> LP-118: New workflow to rebuild the Review App.

.gitlab-ci.yml, composer.lock, config/default/core.date_format.event_date_formatted.yml, config/default/core.date_format.short_formatted_event_date.yml
Changes from this:
---
to this:
Changes have already been applied to production.
=> FOS-101: Any hour specified in am/pm converted to 12-hour numbering

config/default/preview_link.settings.yml
Config change to allow preview links to reference multiple nodes
=> feat(LP-74): Preview Link multiple pages

composer.json, composer.lock, config/default/core.extension.yml
=> feat(LP-71): What Links Here module.

.gitignore, composer.json, composer.lock
https://eccservicetransformation.atlassian.net/browse/LP-216
Updates Gin theme to repair broken dropbuttons
Updates Office Hours module to repair broken functionality in contact component.
=> 202409 dropbuttons lp 216

config/default/core.entity_form_display.geo_entity.address.default.yml, config/default/core.entity_form_display.node.localgov_directories_org.default.yml, config/default/core.entity_form_display.node.localgov_directories_page.default.yml, config/default/core.entity_view_display.geo_entity.address.default.yml, config/default/core.entity_view_display.node.localgov_directories_org.default.yml, config/default/core.entity_view_display.node.localgov_directories_org.directory_index.yml, config/default/core.entity_view_display.node.localgov_directories_org.teaser.yml, config/default/core.entity_view_display.node.localgov_directories_page.default.yml, config/default/core.entity_view_display.node.localgov_directories_page.directory_index.yml, config/default/core.entity_view_display.node.localgov_directories_page.search_index.yml, config/default/core.entity_view_display.node.localgov_directories_page.search_result.yml, config/default/core.entity_view_display.node.localgov_directories_page.teaser.yml, config/default/field.field.node.localgov_directories_org.body.yml, config/default/field.field.node.localgov_directories_org.field_dir_org_how_to_access.yml, config/default/field.field.node.localgov_directories_org.field_directory_org_age.yml, config/default/field.field.node.localgov_directories_page.body.yml, config/default/field.field.node.localgov_directories_page.field_directory_page_access.yml, config/default/field.field.node.localgov_directories_page.field_directory_page_age.yml, config/default/field.storage.node.field_dir_org_how_to_access.yml, config/default/field.storage.node.field_directory_org_age.yml, config/default/field.storage.node.field_directory_page_access.yml, config/default/field.storage.node.field_directory_page_age.yml
https://eccservicetransformation.atlassian.net/browse/LP-212
Adds new text fields to Directory Page content type and Directory organisation, displays their labels.
=> 202409 directories lp 212

.gitlab-ci.yml, composer.lock
- Drupal core update
- Replace apk with apt-get in gitlab-ci
Pipelines started failing recently as apk isn't in the new Docker image
https://techcommunity.microsoft.com/t5/azure-tools-blog/azure-cli-docker-container-base-linux-image-is-now-azure-linux/ba-p/4236248
=> chore(): Drupal core update.

.ddev/commands/web/phpunit, .gitlab-ci.yml, composer.json, composer.lock, config/default/autosave_form.settings.yml, config/default/core.entity_form_display.node.localgov_directories_org.default.yml, config/default/core.entity_form_display.node.localgov_directories_page.default.yml, patches/localgov_workflows_delete_service_contact.patch, phpcs-ecc.xml, phpunit-ecc.xml, phpunit-required.xml, web/modules/custom/ecc_subsites/config/schema/ecc_subsites.schema.yml
- LP-90: Prevent deletion of a service contact if they own pages.
- LP-108: Add Parents to Content menu and local tasks
- LP-106: Preparation for running PHPUnit tests in pipeline
- Fix schema for ecc_subsites
=> Release 2 QA fixes

composer.json, composer.lock, config/default/autosave_form.settings.yml, config/default/core.entity_form_display.node.localgov_publication_page.default.yml, config/default/core.entity_view_display.node.localgov_publication_cover_page.teaser.yml, config/default/core.entity_view_display.node.localgov_publication_page.default.yml, config/default/core.entity_view_display.node.localgov_publication_page.teaser.yml, config/default/core.extension.yml, config/default/node.type.localgov_publication_cover_page.yml, config/default/node.type.localgov_publication_page.yml
=> feat(ECCW-696): LP-146: Install new version of autosave module

.gitlab-ci.yml
=> ci(): Change container name to portalrb

composer.lock, config/default/core.entity_view_display.node.localgov_guides_page.default.yml
=> fix(LP-233): Hide "Publish/ unpublish with parent" field on guide pages.

composer.lock
=> chore(ECCW-713): Drupal core 10.3.8 for security updates

composer.lock
=> Security updates - Drupal 10.3.10, phpspreadsheet

composer.lock
=> Release 202412-02

config/default/core.entity_form_display.node.localgov_directories_page.default.yml, config/default/core.entity_view_display.node.localgov_directories_page.default.yml, config/default/core.entity_view_display.node.localgov_directories_page.directory_index.yml, config/default/core.entity_view_display.node.localgov_directories_page.search_index.yml, config/default/core.entity_view_display.node.localgov_directories_page.search_result.yml, config/default/core.entity_view_display.node.localgov_directories_page.teaser.yml, config/default/field.field.node.localgov_directories_page.localgov_paragraph_content.yml
https://eccservicetransformation.atlassian.net/browse/LP-291
adds existing paragraph field to directory pages content type
=> Add paragraphs to directory pages

config/default/facets.facet.localgov_directories_facets.yml
https://eccservicetransformation.atlassian.net/browse/LP-300
Config change to how facets work.
=> Adjust directory facets to use AND between facet groups

composer.lock
updates theme to latest 1.1.17
=> Update ecc_theme to 1.1.17

composer.lock
Updates the theme to use latest: 1.1.20
=> Update theme to 1.1.20

composer.lock
updgrade theme to use latest 1.1.21
=> ECC Theme v 1.1.21

config/default/facets.facet.localgov_directories_facets.yml
Turns off result count from facets for directory channel embed 
https://eccservicetransformation.atlassian.net/browse/LP-324
=> Hide result counts on facets.

config/default/core.entity_form_display.node.localgov_directory.default.yml, config/default/core.entity_view_display.node.localgov_directory.default.yml, config/default/core.entity_view_display.node.localgov_directory.grid_item.yml, config/default/core.entity_view_display.node.localgov_directory.search_index.yml, config/default/core.entity_view_display.node.localgov_directory.search_result.yml, config/default/core.entity_view_display.node.localgov_directory.teaser.yml, config/default/field.field.node.localgov_directory.localgov_paragraph_content.yml
Add rich content and layouts field to directory channel content type.
https://eccservicetransformation.atlassian.net/browse/LP-320
=> Add rich content and layouts to directory channel pages

composer.lock
Update theme to 1.1.23
https://eccservicetransformation.atlassian.net/browse/LP-308
=> Update theme to 1.1.23

composer.lock
gets latest theme
https://eccservicetransformation.atlassian.net/browse/LP-308
=> Update theme to 1.1.24

composer.lock
Update theme to 1.1.25
https://eccservicetransformation.atlassian.net/browse/LP-334
=> Update theme to 1.1.25

composer.lock
https://eccservicetransformation.atlassian.net/browse/LP-339
=> Update theme to 1.1.26

composer.lock
https://eccservicetransformation.atlassian.net/browse/LP-339
=> Update theme to 1.1.27

composer.lock
=> Merge to 'main' for deployment.

composer.json, composer.lock
Update theme to 1.1.31
Jira https://eccservicetransformation.atlassian.net/browse/LP-285
=> Update theme to 1.1.31

composer.json, composer.lock, config/default/core.extension.yml, config/default/masquerade.settings.yml
https://eccservicetransformation.atlassian.net/jira/software/projects/LP/boards/25?selectedIssue=LP-352
install and enable Masquerade module.
Only available to admins.
=> 202503 masquerade lp 352

config/default/webform.settings.yml
Restrict webform submission exporters to XLSX and set it as default.
https://eccservicetransformation.atlassian.net/browse/LP-235
=> Restrict webform exporters to XLSX and make it default.

composer.json, composer.lock
pulls in latest theme version
https://eccservicetransformation.atlassian.net/browse/LP-354
=> Update theme to 1.1.32

composer.lock, config/default/core.entity_form_display.paragraph.iframe.default.yml, config/default/core.entity_view_display.paragraph.iframe.default.yml, config/default/field.field.paragraph.iframe.field_p_iframe_size.yml, config/default/field.field.paragraph.iframe.field_p_iframe_url.yml, config/default/field.storage.paragraph.field_p_iframe_size.yml, config/default/field.storage.paragraph.field_p_iframe_url.yml, config/default/paragraphs.paragraphs_type.iframe.yml
Creates a paragraph entity to allow editors to use an iframe to embed something.
All config. No custom code. Includes new theme version.
https://eccservicetransformation.atlassian.net/browse/LP-357
=> Create iframe embed paragraph component.

composer.lock
theme to 1.1.34
for https://eccservicetransformation.atlassian.net/browse/LP-341
=> Set theme to 1.1.34

config/default/field.field.node.localgov_directories_page.localgov_paragraph_content.yml, config/default/field.field.node.localgov_directory.localgov_paragraph_content.yml, config/default/field.field.node.localgov_directory_promo_page.localgov_paragraph_content.yml, config/default/field.field.node.localgov_services_page.localgov_paragraph_content.yml, config/default/field.field.node.localgov_subsites_overview.localgov_subsites_content.yml, config/default/field.field.node.localgov_subsites_page.localgov_subsites_content.yml
the last PR had the bits of the component... so now we expose it to the layout-paragraphs fields.
https://eccservicetransformation.atlassian.net/browse/LP-357
=> Expose iframe component to LGD layout paragraphs

config/default/user.role.localgov_editor.yml
Allow editors to be able to edit and delete polls
https://eccservicetransformation.atlassian.net/browse/LP-277
=> allow editors to edit and delete polls

config/default/user.role.localgov_news_editor.yml
allow `news editors` to administer polls in addition to editors
https://eccservicetransformation.atlassian.net/browse/LP-277
=> Aloow news editors to edit polls

config/default/user.role.localgov_news_editor.yml
https://eccservicetransformation.atlassian.net/browse/LP-277
=> Allow news editors to access poll overview page

composer.lock
following on from update to ecc_parents, pull in the new version
https://eccservicetransformation.atlassian.net/browse/LP-335
=> Update ecc parents to 1.0.3
